Manufacturer.create(name: "Tesla", country: "USA")
Manufacturer.create(name: "Land Rover", country: "UK")
Manufacturer.create(name: "Audi", country: "Germany")
Manufacturer.create(name: "Ferrari", country: "Italy")
Manufacturer.create(name: "Hyundai", country: "South Korea")
