source "https://rubygems.org"

gem "sinatra"
gem "sinatra-activerecord"
gem "sinatra-flash"
gem "pg"
gem "rake"

group :development, :test do
  gem "rspec"
  gem "capybara"
  gem "database_cleaner"
end
