development:
  adapter: postgresql
  encoding: unicode
  database: brussels_blog_development
  pool: 5
  username:
  password:

# Configure the database used when in the test environment
test:
  adapter: postgresql
  encoding: unicode
  database: brussels_blog_test
  pool: 5
  username:
  password:

# Configure the database used when in the production environment
production:
  adapter: postgresql
  encoding: unicode
  database: brussels_blog_production
  pool: 5
  username:
  password:
